### ISSUE TITLE
Manny stuck at the scene in the petrified forest with the creepy key

### ISSUE THREAD

**Issue by JenniBee** [tobiaspfaff/grim_mouse#1] opened 2014-02-14 17:55 UTC
At the scene in the petrified forest with the creepy key. Manny won't go right on the path to get back to the main forest, he just goes straight up, but there doesn't seem to be any clickable areas to make him turn right. I have to use the keyboard here in order to make him move. If I turn him right, I'm able to click on the screen to make him move to the right. 

![stuck](https://f.cloud.github.com/assets/782034/2173386/025f4416-95a1-11e3-8a8c-99ce9c6686e5.png)

The hotspot only seems to be wonky when you're on foot, as I tried it in the Bone Wagon, and you can get past that part perfectly with a mouse when you're riding it out.

**Comment by tobiaspfaff** [comment] 2014-02-23 03:38
I can't reproduce this one -- do you have a savegame, or more detailed instructions on how to get stuck there ? Also, which hotspot doesn't work; the one at the ramp?

**Comment by JenniBee** [comment] 2014-03-05 11:53
[Here's a save file](http://www.jennifermcmurray.com/grim00.gsv)

If you go up to the rocks and then try to go back, you get stuck.

Another hotspot that is hard to find in this area is the bonewagon (I did manage it the first time I tried, as I said above, but when I retried it I couldn't find the hotspot to hop back on the bonewagon).

[Here's a savegame with the bonewagon]([http://www.jennifermcmurray.com/grim01.gsv])

**Comment by tobiaspfaff** [comment] 2014-03-07 19:43
Aha! Thanks for posting the save games, this clears things up.
It looks like this is caused by the savegame-bug, which screwed up the hotspot coordinates in 0.1 and 0.2.
It's fixed in 0.3, so I'm closing this bug. You can verify by running v0.3, loading your savegame and manually updating hotspot coordinates (the old, screwed up coordinates are still saved in the game state). To do this, switch to dev mode (Shift+Z) and then hit F5 to update. If things are still messed up, please re-open this bug.

**Closed as completed by tobiaspfaff** 2014-03-07 19:43 UTC
